# https://github.com/Kaggle/docker-python/releases
FROM gcr.io/kaggle-gpu-images/python:latest

WORKDIR /workspace

# その他のライブラリ
RUN pip install --no-cache-dir \
    ruff \
    hydra-core \
    python-dotenv \
    rootutils \
    fire
